### ISSUE TITLE
Bulk Update Plugins

### ISSUE THREAD

**Issue by devolution007** [FestingerVault/festingervault#33]
Hello @MartinFestingerVault, I'm encountering an issue while updating multiple plugins at once.
![image](https://github.com/user-attachments/assets/01b8c1dd-883a-413e-9aeb-37b506c8f824)

**Comment by MartinFestingerVault** [comment]
Thanks for your feedback @devolution007.

Could you please send me temporary admin access to hello@festingervault.com and I'll check out the issue.

**Comment by devolution007** [comment]
Hi @MartinFestingerVault, thanks for your prompt response. I've granted you access to my WordPress site using the email you provided. Here is the password: `e8i)jsakh^xQlGuKfGzasVLH`.

**Comment by MartinFestingerVault** [comment]
I just checked your issue and you haven't activated your license key. ;) 

![image](https://github.com/user-attachments/assets/23ccdebf-1080-4a19-bd06-eaae848e3229)

**Comment by devolution007** [comment]
Hi @MartinFestingerVault, I've removed the domain and re-added the license key. Please check it again. Thanks!
![image](https://github.com/user-attachments/assets/5840359e-c065-498a-938e-4a47491247b6)

**Comment by devolution007** [comment]
Hi @MartinFestingerVault, I just tested it on my other website, and everything works great there. It may be a glitch or bug, and I hope it gets fixed in the update. Everything else is perfect.
