### ISSUE TITLE
Add queue for automatic update schedule

### ISSUE THREAD

**Issue by MartinFestingerVault** [FestingerVault/festingervault#59]
It could be nice if there is some way to access and check the queue and status of the auto-update function somewhere in the background, like we can check the cron in wordpress, in case one needs to find problems, but if it functions that would work too.

Looking at the queue (and log?) might also give a way to report possible updating problems back to users. Although when auto-update works, one might not think to check a queue or log and needs to be actively informed when there are update problems (e-mail?).

https://meta.festingervault.com/t/its-here-the-all-new-festinger-vault-plugin-is-ready-for-download/99904/141?u=martin

**Comment by MartinFestingerVault** [comment]
Another minor thing I noticed is that I selected most of the items in the updates page and subsequently used the action pull down to set them all to auto-update. That went allright, but after some time seeing the messages on the left popping up, I decided to go to another page in FV (getting a bit impatient perhaps).

It seems that when I do that, the processing of my action is being stopped and it is not really a queue process that is separate from the page. Setting about 50 plugins to auto-update makes some wait, since they seem to be processed one at the time.

No problem when one waits long enough before leaving, but one need to know that then and be patient enough to do so.

The best solution for me is that I start the process and it is handled on the background without further needing my presence, but the current implementation implemented it a process that I actually need to wait for, although it leaves my screen free and I can leave and inadvertently break the processing by doing so.

Perhaps some more guidance on that fact? A popup telling me that if I leave this will break of this process and asks to please wait till its done would be an idea, but then one expects some progress indicator. Such popups happen f.i. when I try to leave gutenberg editor without saving updates (or close the browser). But there could be other solutions off course. Now I can leave expecting that the process will finish, while it doesn’t.

**Comment by ssovit** [comment]
Autoupdate issue is fixed with new update on 5.0.0-beta.2.4.3.1

**Comment by hansschuijff** [comment]
The second part of this issue should perhaps be an issue on it's own, but isn't yet addressed. 

Perhaps there can be a more efficient way to process bulk setting of the auto-update switch, that reduces the waiting time. Setting the switch one after the other seems an inefficient way of handling a bulk update.

What I have noticed is that even if I wait for all success messages to end, still there are selected items that are not set to auto-update. I haven't tested it further, than just noticing that not all selected products now have an auto-update switch enabled, but it seems to miss some when I try to bulk set a lot of them at the time. Perhaps that should be tested better, if its an async issue or something like that. If I can't trust that all selected items are actually switched when I ask it, even when there are no errors show, that is not a good thing.

**Comment by MartinFestingerVault** [comment]
We have integrated the auto scheduler for this purpose, which will solve the issue.
