### ISSUE TITLE
Multi Site Compatibility

### ISSUE THREAD

**Issue by MartinFestingerVault** [FestingerVault/festingervault#68]
It will be wonderfull if the FV plugin will support multisite and appears only at the network admin page to update all the plugins at network level.

https://meta.festingervault.com/t/fv-plugin-multisite-support/34231

**Comment by ssovit** [comment]
Plugin can be activated on main site and mark auto updates to receive auto-updates. Updates are done to theme/plugin files they live in `wp-content/themes`/`wp-content/plugins`, so having different settings and auto-update rules would not have any significant impact if `site-a` updates a plugin `plugin-1`, that would also affect `site-b` if they use it, have activated it and doesn't have enabled auto-activate for `plugin-1`
