### ISSUE TITLE
Update page should be based on installed plugins/themes

### ISSUE THREAD

**Issue by hansschuijff** [FestingerVault/festingervault#73]
I've been thinking about the doublures and mistakes on the update page listed products. 

It seems there are a few problems in there:
1. different plugins/themes using the same slug
2. zip-files that contain different plugins/themes than they are supposed to and that are matched by the content of the zip rather than the actual product.
3. duplicate entries of the same plugin in FV (f.i. by FV adding an update as a separate product). 
4. not connecting installed products to a single product in FV

I've already send a list of erroneous matches to the support page and found some new ones too, but the base problem seems to be that the updates list is mainly a list of FV products matched with installed plugins/themes, rather than a list of installed products in the site that are managed by FV. I think there is a difference and the latter is the correct approach.

When FV Updates gives a list of installed plugins/themes of the website, there can only be one of each and no more and FV is forced to determine what specific product is the correct match and could still make errors in that matching, but they would be more obvious.

For me as a website manager it would be a list of plugins and themes as they are named anywhere else in my website and I could recognize them as such.

If FV would find more than one match and could not make a decision the problem would be clear immediately and FV should not make a decision, rather give the decision back to the website manager.

FV could remember the matches and communicate about known matches by the fv-id rather than less specific criteria, leaving only the non-determined matched plugins/themes as an issue to be solved. The id's could be remembered in the DB somewhere.

Items that are from WordPress.org don't ever have to be matched, since they are handled outside of fv, so they can be marked too.

That leaves only plugins/themes that are manually installed outside of FV that might need to be matched and will probably be a small set.

I could imagine that a list could show a dropdown for the products that are ambiguous in the match (more than one result) so the site manager can select the right one.

But showing installed product as is done in WP itself would be a better list than starting with the FV result that could have multiple duplicates in it.

The problem is not as much that it has duplicates, but that it can have duplicates by not basing it on the installed products only. It is easier to do it like it is, but that enables errors too.

If FV could mark each installed plugin/theme with an id of an indication of "not applicable" then the list to consider would be smaller and errors would me more visible, since someone would call them out earlier.

**Comment by MartinFestingerVault** [comment]
Thanks for your suggestion @hansschuijff.

We're updating our slug algorithm that allows you to set a hardcoded slug for each item.

https://github.com/FestingerVault/festingervault/issues/53
