### ISSUE TITLE
Showing Incorrect Details of plugin

### ISSUE THREAD

**Issue by devolution007** [FestingerVault/festingervault#75]
Hi @MartinFestingerVault hope you are having a great day!

On the website, it shows that the details column was last updated on August 8, 2024.
![image](https://github.com/user-attachments/assets/2fbed7d4-c629-42e9-8585-fbc00e775936)

But, On the festinger plugin it shows that it was updated on August 15, 2024
![image](https://github.com/user-attachments/assets/d08e8dba-2940-4336-a307-5db955f3a560)

Virus Total is not working properly as it continuously scans but doesn't display the results.
![image](https://github.com/user-attachments/assets/e2db762f-2450-4923-9c6b-88e201bfdc77)

**Comment by MartinFestingerVault** [comment]
Hi @devolution007,

Thanks for the report. Both issues have been resolved. Please check.
