### ISSUE TITLE
Clicking Auto-update switch toggles more than one switch

### ISSUE THREAD

**Issue by hansschuijff** [FestingerVault/festingervault#80]
I have Seopress Pro installed on a website and right now it means that the updates page shows both this plugin as OceanWP Demo Import. Today I noticed that SeoPress Pro wasn't marked for autoupdate so I used the toggle to switch it on.

In doing that I noticed that it also switched autoupdate on for OceanWP Demo Import, a plugin I haven't installed and that is added incorrectly in the page. So as a user I don't want autoupdate to switch on for this incorrectly added plugin.

I understand that the functionality is build around the slug rather than the individual plugin, supposing that the slug will be unique, but it isn't. So now the interface behaves confusing from my perspective.

Somehow it needs to be build around the individual product and not on info that I cannot even see in the page.

**Comment by MartinFestingerVault** [comment]
This issue has been resolved with the latest version of our update.

Please update to the latest version. 

https://github.com/FestingerVault/festingervault/tree/beta-release
